
name: deploy

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true
      PORT:
        required: true
      ORIGIN_PATH:
        required: true
      REMOTE_PATH:
        required: true
      PREPARE_COMMAND:
        required: true
      ACTION_COMMAND:
        required: true
      COMMAND:
        required: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/deploy-action@main
        timeout-minutes: 2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_PATH: ${{ secrets.ORIGIN_PATH }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          PREPARE_COMMAND: ${{ secrets.PREPARE_COMMAND }}
          ACTION_COMMAND: ${{ secrets.ACTION_COMMAND }}
